### ISSUE TITLE
How to fix ERROR: problem running ufw-init?

### ISSUE THREAD

**Issue by juragandotid** [jirislav/mailinabox#14]
I'm order vps on godaddy, i'm install on vps ubuntu 16.04 

i'm have problems when proscess installing after proccess set hostname :
ERROR: problem running ufw-init
modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open b                                                                                        uiltin file '/lib/modules/4.4.0-042stab120.16/modules.builtin.bin'
modprobe: FATAL: Module nf_conntrack_ftp not found in directory /lib/modules/4.4                                                                                        .0-042stab120.16
modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open b                                                                                        uiltin file '/lib/modules/4.4.0-042stab120.16/modules.builtin.bin'
modprobe: FATAL: Module nf_nat_ftp not found in directory /lib/modules/4.4.0-042                                                                                        stab120.16
modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open b                                                                                        uiltin file '/lib/modules/4.4.0-042stab120.16/modules.builtin.bin'
modprobe: FATAL: Module nf_conntrack_netbios_ns not found in directory /lib/modu                                                                                        les/4.4.0-042stab120.16
iptables-restore: line 4 failed
iptables-restore: line 77 failed
iptables-restore: line 31 failed
sysctl: permission denied on key 'net.ipv4.tcp_sack'

Problem loading ipv6 (skipping)
Problem running '/etc/ufw/before.rules'
Problem running '/etc/ufw/user.rules'

can u help me?

Thank you.

**Comment by juragandotid** [comment]
I have resolve this.

I'm explaind how to fix this.


install ufw first than add this bash and execute it


#!/bin/bash
sed '/A ufw-after-input -m addrtype --dst-type BROADCAST -j ufw-skip-to-policy-input/s/^/#/' /etc/ufw/after.rules > ~/temp
cp temp /etc/ufw/after.rules
sed '/-A ufw-not-local -m addrtype --dst-type LOCAL -j RETURN/s/^/#/' /etc/ufw/before.rules > ~/temp
cp temp /etc/ufw/before.rules
sed '/-A ufw-not-local -m addrtype --dst-type MULTICAST -j RETURN/s/^/#/' /etc/ufw/before.rules > ~/temp
cp temp /etc/ufw/before.rules
sed '/-A ufw-not-local -m addrtype --dst-type BROADCAST -j RETURN/s/^/#/' /etc/ufw/before.rules > ~/temp
cp temp /etc/ufw/before.rules
rm -f /sbin/modprobe
ln -s /bin/true /sbin/modprobe
rm -f /sbin/sysctl
ln -s /bin/true /sbin/sysctl
apt-get -y purge rsyslog
apt-get install -y syslog-ng
echo start on startup >> /etc/init/ufw.conf
echo #console output >> /etc/init/ufw.conf
sed '/IPV6=yes/s/yes/no/' /etc/default/ufw > ~/temp
cp temp /etc/default/ufw
rm ~/temp


Thank you.

**Comment by juragandotid** [comment]
remove apt-get -y purge rsyslog from bash script

**Comment by jirislav** [comment]
Hi, I see your problem & my first thought is: Did you try to install MIAB on a fresh Ubuntu 16.04? Because i can hardly imagine that GoDaddy would let you start with a broken VPS, where the very essential part of the OS, `modprobe`, would have problems resolving binary libraries.

I've looked into your solution and I don't like it at all. Replacing mandatory binaries with `/bin/true` is a very bad idea. You should avoid this at all cost.

I recommend you to try spinning up a fresh Ubuntu 16.04 machine and following only those instructions on the homepage of this project, nothing more.

If that doesn't help, you should consider moving to another VPS provider, such as DigitalOcean and such. This step will certainly solve your issue, so I'm closing it for now.

Btw, here are some tips at the end:

I see you're using:
```bash
sed EXPRESSION FILE > TMP_FILE 
cp TMP_FILE FILE
```

You should instead use `in place` flag for sed to edit the file directly:
```bash
sed -i EXPRESSION FILE
```

The same principle applies for instead of copying & removing the file:
```bash
cp TMP_FILE FILE
rm TMP_FILE
```

Just move the file:
```bash
mv TMP_FILE FILE
```
