### ISSUE TITLE
This machine has 511 MB memory

### ISSUE THREAD

**Issue by FahmiRaazali** [jirislav/mailinabox#6]
Hi!

How to install if I got this error?

```
Your Mail-in-a-Box needs more memory (RAM) to function properly.
Please provision a machine with at least 512 MB, 1 GB recommended.
This machine has 511 MB memory.
```

Thank you.

**Comment by jirislav** [comment]
Hi,

I think, there should be no restriction to users at all if they want to install MIAB. My opinion is that it's their responsibility to provide the machine enough resources to run it properly, so that's why I've right now transformed that error to just warn the user about recommended setup resources (I've actually set 128 MB to the absolute minimum).

So consider this fixed by checkout out current master branch & installing from it:
```bash
git fetch --all
git checkout origin/master
sudo setup/start.sh 
```

**Comment by FahmiRaazali** [comment]
I will try this again.

Thank you.

**Comment by jirislav** [comment]
you're welcome :smiley:

**Comment by jirislav** [comment]
you didn't post any feedback, so I suppose this problem is solved, feel free to reopen if I'm wrong
